"""Architecture tests for clean vibe tags and IUCN conservation fields.

These tests protect the final architecture required by the assignment:
- tags_de_busqueda is only for structured vibe search: color + habitat + size.
- names, taxonomy, source queries, Wikidata/common-name noise and narrative text stay out of tags_de_busqueda.
- search_document can keep names/taxonomy for fallback search.
- IUCN fields keep official status separate from missing data.
"""

from __future__ import annotations

import pandas as pd

from src.search_tags import add_search_tags_to_encyclopedia


def test_tags_de_busqueda_contains_only_vibe_tags() -> None:
    """Search tags must not include names, taxonomy, source queries or narrative/profile text."""

    df = pd.DataFrame(
        [
            {
                "scientific_name": "Panthera leo (Linnaeus, 1758)",
                "canonical_scientific_name": "Panthera leo",
                "vernacular_names": "Lion | León | Löwe | лев",
                "kingdom": "Animalia",
                "taxon_class": "Mammalia",
                "taxon_order": "Carnivora",
                "family": "Felidae",
                "genus": "Panthera",
                "source_queries": "big_cats_felidae",
                "profile_text": "Large cat of the savanna.",
                "search_document": "Panthera leo Lion León Felidae",
            },
            {
                "scientific_name": "Papilio machaon Linnaeus, 1758",
                "canonical_scientific_name": "Papilio machaon",
                "vernacular_names": "Swallowtail butterfly | mariposa",
                "kingdom": "Animalia",
                "taxon_class": "Insecta",
                "taxon_order": "Lepidoptera",
                "family": "Papilionidae",
                "genus": "Papilio",
                "source_queries": "butterflies_lepidoptera",
                "profile_text": "Butterfly.",
                "search_document": "Papilio butterfly mariposa",
            },
        ]
    )

    tagged_df = add_search_tags_to_encyclopedia(df)

    lion_tags = tagged_df.iloc[0]["tags_de_busqueda"].lower()
    butterfly_tags = tagged_df.iloc[1]["tags_de_busqueda"].lower()

    # Positive checks: the field contains structured vibe tags generated by feature engineering.
    assert "large" in lion_tags
    assert "brown" in lion_tags or "grey" in lion_tags or "gray" in lion_tags
    assert "small" in butterfly_tags
    assert "colorful" in butterfly_tags or "bright" in butterfly_tags or "multicolor" in butterfly_tags

    # Negative checks: these values belong to display/fallback search, not structured vibe tags.
    forbidden_terms = [
        "panthera",
        "leo",
        "lion",
        "león",
        "lowe",
        "лев",
        "felidae",
        "mammalia",
        "carnivora",
        "big_cats_felidae",
        "papilio",
        "machaon",
        "butterfly",
        "mariposa",
        "lepidoptera",
        "papilionidae",
        "butterflies_lepidoptera",
    ]

    for term in forbidden_terms:
        assert term not in lion_tags
        assert term not in butterfly_tags

    # Important: profile/narrative text must not leak into tags_de_busqueda either.
    # The word "savanna" appears only in profile_text above, so expecting it in tags would
    # reintroduce the old text-noise architecture.
    assert "savanna" not in lion_tags


def test_search_document_can_keep_names_for_fallback_search() -> None:
    """search_document can keep names/taxonomy while tags_de_busqueda stays clean."""

    df = pd.DataFrame(
        [
            {
                "scientific_name": "Phoenicopterus roseus",
                "canonical_scientific_name": "Phoenicopterus roseus",
                "vernacular_names": "flamingo|flamenco|фламинго",
                "kingdom": "Animalia",
                "taxon_class": "Aves",
                "family": "Phoenicopteridae",
                "search_document": "existing document",
            }
        ]
    )

    result = add_search_tags_to_encyclopedia(df)
    tags = result.loc[0, "tags_de_busqueda"].lower()
    document = result.loc[0, "search_document"].lower()

    assert "flamingo" not in tags
    assert "фламинго" not in tags
    assert "phoenicopterus" not in tags

    assert "phoenicopterus roseus" in document
    assert "flamingo" in document
    assert "phoenicopteridae" in document


def test_iucn_official_status_is_not_educational_fallback() -> None:
    """Official IUCN fields must remain explicit and separate from NO_DATA fallback."""

    df = pd.DataFrame(
        [
            {
                "scientific_name": "Panthera leo",
                "canonical_scientific_name": "Panthera leo",
                "kingdom": "Animalia",
                "taxon_class": "Mammalia",
                "iucn_category": "VU",
                "iucn_status_label": "Vulnerable",
                "iucn_source": "IUCN Red List",
                "iucn_is_official": True,
            },
            {
                "scientific_name": "Unknown species",
                "canonical_scientific_name": "Unknown species",
                "kingdom": "Animalia",
                "taxon_class": "Insecta",
                "iucn_category": "NO_DATA",
                "iucn_status_label": "Sin datos IUCN",
                "iucn_source": "No IUCN data",
                "iucn_is_official": False,
            },
        ]
    )

    result = add_search_tags_to_encyclopedia(df)

    assert result.loc[0, "iucn_category"] == "VU"
    assert result.loc[0, "iucn_source"] == "IUCN Red List"
    assert bool(result.loc[0, "iucn_is_official"]) is True

    assert result.loc[1, "iucn_category"] == "NO_DATA"
    assert result.loc[1, "iucn_source"] == "No IUCN data"
    assert bool(result.loc[1, "iucn_is_official"]) is False
